import Head from 'next/head'
import styles from '../../styles/Home.module.css'

export default function Header() {
    return (
        <div>
            <Head>
                <title>Chat Chat</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <header className={styles.header}>
                <h1 className={styles.logo}>
                    <a href="">Chat Chat!</a>
                </h1>
            </header>
        </div>

    );
}